# Generated by Django 3.1.3 on 2020-11-15 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=11)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('about_me', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('salary_amount', models.IntegerField()),
                ('salary_frequency', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=10)),
                ('academic_level', models.CharField(blank=True, choices=[('no formal qualification', 'No Formal Qualification'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bsc', "Bachelor's Degree"), ('msc', "Master's Degree")], max_length=25)),
                ('years_of_experience', models.CharField(blank=True, choices=[('0', '0-1'), ('1', '1-2'), ('2', '2-3'), ('3', '3-4'), ('4', '4-5'), ('5', '5-6'), ('6', '6-7'), ('7', '7-8'), ('8', '8-9'), ('9', '9-10'), ('10', '10-11')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone_no', models.CharField(blank=True, max_length=11)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='stack', to='account.TechStack'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
