# Generated by Django 3.1.3 on 2020-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201115_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='salary_amount',
            field=models.IntegerField(null=True),
        ),
    ]
