# Generated by Django 3.1.3 on 2020-11-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201115_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0', '0-1 years'), ('1', '1-2 years'), ('2', '2-3 years'), ('3', '3-4 years'), ('4', '4-5 years'), ('5', '5-6 years'), ('6', '6-7 years'), ('7', '7-8 years'), ('8', '8-9 years'), ('9', '9-10 years'), ('10', '10-11 years')], max_length=10),
        ),
    ]
