# Generated by Django 3.1.3 on 2020-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201115_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
