# Generated by Django 3.1.3 on 2020-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201115_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
