# Generated by Django 3.1.3 on 2020-11-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_for_by',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='account.CandidateProfile'),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='account.organizationprofile'),
            preserve_default=False,
        ),
    ]
