# Generated by Django 3.1.3 on 2020-11-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201116_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('fresh', 'Fresh'), (1, 'less than 1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years +')], max_length=23),
        ),
    ]
